name: Release

on:
  release:
    types:
      - created

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go 1.x
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build arm
        run: go build -o fanshim_linux_arm .
        env:
          GOOS: linux
          GOARCH: arm

      - name: Build arm64
        run: go build -o fanshim_linux_arm64 .
        env:
          GOOS: linux
          GOARCH: arm64

      - name: Upload arm binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./fanshim_linux_arm
          asset_name: fanshim_linux_arm
          asset_content_type: application/octet-stream

      - name: Upload arm64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./fanshim_linux_arm64
          asset_name: fanshim_linux_arm64
          asset_content_type: application/octet-stream